#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode.
if (file_exists(__DIR__.'/storage/framework/maintenance.php')) {
    require __DIR__.'/storage/framework/maintenance.php';
}

// Register the Composer autoloader.
require __DIR__.'/vendor/autoload.php';

// Bootstrap the Laravel application.
$app = require_once __DIR__.'/bootstrap/app.php';

// Run the console application.
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
